# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searchwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!
'''
Copyright © 2018 UnclassedPenguin
App: Animal Tracker
Author: UnclassedPenguin
Description: An app to keep track of your Animals
'''
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(477, 473)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 10, 171, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(300, 40, 131, 213))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.distinctcbButton = QtWidgets.QCheckBox(self.layoutWidget)
        self.distinctcbButton.setObjectName("distinctcbButton")
        self.gridLayout_2.addWidget(self.distinctcbButton, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.orderbyBox = QtWidgets.QComboBox(self.layoutWidget)
        self.orderbyBox.setObjectName("orderbyBox")
        self.gridLayout_2.addWidget(self.orderbyBox, 5, 0, 1, 1)
        self.tableBox = QtWidgets.QComboBox(self.layoutWidget)
        self.tableBox.setObjectName("tableBox")
        self.gridLayout_2.addWidget(self.tableBox, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.orderby2Box = QtWidgets.QComboBox(self.layoutWidget)
        self.orderby2Box.setObjectName("orderby2Box")
        self.gridLayout_2.addWidget(self.orderby2Box, 7, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 6, 0, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 40, 221, 143))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 3, 0, 1, 1)
        self.rfid2Entry = QtWidgets.QLineEdit(self.layoutWidget1)
        self.rfid2Entry.setObjectName("rfid2Entry")
        self.gridLayout_3.addWidget(self.rfid2Entry, 1, 1, 1, 1)
        self.id2Entry = QtWidgets.QLineEdit(self.layoutWidget1)
        self.id2Entry.setObjectName("id2Entry")
        self.gridLayout_3.addWidget(self.id2Entry, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.name2Entry = QtWidgets.QLineEdit(self.layoutWidget1)
        self.name2Entry.setObjectName("name2Entry")
        self.gridLayout_3.addWidget(self.name2Entry, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.group2Box = QtWidgets.QComboBox(self.layoutWidget1)
        self.group2Box.setObjectName("group2Box")
        self.gridLayout_3.addWidget(self.group2Box, 0, 1, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 250, 441, 112))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.namecbButton = QtWidgets.QCheckBox(self.layoutWidget2)
        self.namecbButton.setChecked(True)
        self.namecbButton.setObjectName("namecbButton")
        self.gridLayout.addWidget(self.namecbButton, 0, 0, 1, 1)
        self.datecbButton = QtWidgets.QCheckBox(self.layoutWidget2)
        self.datecbButton.setObjectName("datecbButton")
        self.gridLayout.addWidget(self.datecbButton, 0, 1, 1, 1)
        self.gendercbButton = QtWidgets.QCheckBox(self.layoutWidget2)
        self.gendercbButton.setObjectName("gendercbButton")
        self.gridLayout.addWidget(self.gendercbButton, 0, 2, 1, 1)
        self.notescbButton = QtWidgets.QCheckBox(self.layoutWidget2)
        self.notescbButton.setObjectName("notescbButton")
        self.gridLayout.addWidget(self.notescbButton, 0, 3, 1, 1)
        self.rfidcbButton = QtWidgets.QCheckBox(self.layoutWidget2)
        self.rfidcbButton.setObjectName("rfidcbButton")
        self.gridLayout.addWidget(self.rfidcbButton, 1, 0, 1, 1)
        self.bdaycbButton = QtWidgets.QCheckBox(self.layoutWidget2)
        self.bdaycbButton.setObjectName("bdaycbButton")
        self.gridLayout.addWidget(self.bdaycbButton, 1, 1, 1, 1)
        self.weightcbButton = QtWidgets.QCheckBox(self.layoutWidget2)
        self.weightcbButton.setObjectName("weightcbButton")
        self.gridLayout.addWidget(self.weightcbButton, 1, 2, 1, 1)
        self.soldcbButton = QtWidgets.QCheckBox(self.layoutWidget2)
        self.soldcbButton.setObjectName("soldcbButton")
        self.gridLayout.addWidget(self.soldcbButton, 1, 3, 1, 1)
        self.idcbButton = QtWidgets.QCheckBox(self.layoutWidget2)
        self.idcbButton.setObjectName("idcbButton")
        self.gridLayout.addWidget(self.idcbButton, 2, 0, 1, 1)
        self.mothercbButton = QtWidgets.QCheckBox(self.layoutWidget2)
        self.mothercbButton.setObjectName("mothercbButton")
        self.gridLayout.addWidget(self.mothercbButton, 2, 1, 1, 1)
        self.bodyconcbButton = QtWidgets.QCheckBox(self.layoutWidget2)
        self.bodyconcbButton.setObjectName("bodyconcbButton")
        self.gridLayout.addWidget(self.bodyconcbButton, 2, 2, 1, 1)
        self.groupcbButton = QtWidgets.QCheckBox(self.layoutWidget2)
        self.groupcbButton.setObjectName("groupcbButton")
        self.gridLayout.addWidget(self.groupcbButton, 3, 0, 1, 1)
        self.fathercbButton = QtWidgets.QCheckBox(self.layoutWidget2)
        self.fathercbButton.setObjectName("fathercbButton")
        self.gridLayout.addWidget(self.fathercbButton, 3, 1, 1, 1)
        self.hoofconcbButton = QtWidgets.QCheckBox(self.layoutWidget2)
        self.hoofconcbButton.setObjectName("hoofconcbButton")
        self.gridLayout.addWidget(self.hoofconcbButton, 3, 2, 1, 1)
        self.toggleallButton = QtWidgets.QPushButton(self.centralwidget)
        self.toggleallButton.setGeometry(QtCore.QRect(20, 220, 129, 25))
        self.toggleallButton.setObjectName("toggleallButton")
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(200, 380, 263, 58))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.genealogyButton = QtWidgets.QPushButton(self.layoutWidget3)
        self.genealogyButton.setObjectName("genealogyButton")
        self.gridLayout_4.addWidget(self.genealogyButton, 0, 0, 1, 1)
        self.search2Button = QtWidgets.QPushButton(self.layoutWidget3)
        self.search2Button.setObjectName("search2Button")
        self.gridLayout_4.addWidget(self.search2Button, 0, 1, 1, 1)
        self.clear2Button = QtWidgets.QPushButton(self.layoutWidget3)
        self.clear2Button.setObjectName("clear2Button")
        self.gridLayout_4.addWidget(self.clear2Button, 0, 2, 1, 1)
        self.testButton = QtWidgets.QPushButton(self.layoutWidget3)
        self.testButton.setObjectName("testButton")
        self.gridLayout_4.addWidget(self.testButton, 1, 0, 1, 1)
        self.save2Button = QtWidgets.QPushButton(self.layoutWidget3)
        self.save2Button.setObjectName("save2Button")
        self.gridLayout_4.addWidget(self.save2Button, 1, 1, 1, 1)
        self.quit2Button = QtWidgets.QPushButton(self.layoutWidget3)
        self.quit2Button.setObjectName("quit2Button")
        self.gridLayout_4.addWidget(self.quit2Button, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Animal Tracker - Advanced Search"))
        self.label.setText(_translate("MainWindow", "Advanced Search"))
        self.distinctcbButton.setText(_translate("MainWindow", "Distinct"))
        self.label_2.setText(_translate("MainWindow", "Options"))
        self.label_4.setText(_translate("MainWindow", "Order By:"))
        self.label_8.setText(_translate("MainWindow", "Table:"))
        self.label_9.setText(_translate("MainWindow", "Order By 2:"))
        self.label_7.setText(_translate("MainWindow", "Name:"))
        self.label_5.setText(_translate("MainWindow", "RFID:"))
        self.label_6.setText(_translate("MainWindow", "ID:"))
        self.label_3.setText(_translate("MainWindow", "Group:"))
        self.namecbButton.setText(_translate("MainWindow", "Name"))
        self.datecbButton.setText(_translate("MainWindow", "Date"))
        self.gendercbButton.setText(_translate("MainWindow", "Gender"))
        self.notescbButton.setText(_translate("MainWindow", "Notes"))
        self.rfidcbButton.setText(_translate("MainWindow", "RFID"))
        self.bdaycbButton.setText(_translate("MainWindow", "Birthday"))
        self.weightcbButton.setText(_translate("MainWindow", "Weight"))
        self.soldcbButton.setText(_translate("MainWindow", "Sold"))
        self.idcbButton.setText(_translate("MainWindow", "ID"))
        self.mothercbButton.setText(_translate("MainWindow", "Mother"))
        self.bodyconcbButton.setText(_translate("MainWindow", "Body Cond."))
        self.groupcbButton.setText(_translate("MainWindow", "Group"))
        self.fathercbButton.setText(_translate("MainWindow", "Father"))
        self.hoofconcbButton.setText(_translate("MainWindow", "Hoof Cond."))
        self.toggleallButton.setText(_translate("MainWindow", "Select All"))
        self.genealogyButton.setText(_translate("MainWindow", "Genealogy"))
        self.search2Button.setText(_translate("MainWindow", "Search"))
        self.clear2Button.setText(_translate("MainWindow", "Clear"))
        self.testButton.setText(_translate("MainWindow", "Test"))
        self.save2Button.setText(_translate("MainWindow", "Save"))
        self.quit2Button.setText(_translate("MainWindow", "Close"))

