# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searchwindow3.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(616, 339)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 7, 1, 3)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 1, 1, 1)
        self.tableBox = QtWidgets.QComboBox(self.centralwidget)
        self.tableBox.setObjectName("tableBox")
        self.gridLayout.addWidget(self.tableBox, 5, 7, 1, 3)
        self.orderbyBox = QtWidgets.QComboBox(self.centralwidget)
        self.orderbyBox.setObjectName("orderbyBox")
        self.gridLayout.addWidget(self.orderbyBox, 8, 7, 1, 3)
        self.distinctcbButton = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.distinctcbButton.setFont(font)
        self.distinctcbButton.setObjectName("distinctcbButton")
        self.gridLayout.addWidget(self.distinctcbButton, 6, 7, 1, 1)
        self.orderby2Box = QtWidgets.QComboBox(self.centralwidget)
        self.orderby2Box.setObjectName("orderby2Box")
        self.gridLayout.addWidget(self.orderby2Box, 11, 7, 1, 3)
        self.datecbButton = QtWidgets.QCheckBox(self.centralwidget)
        self.datecbButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.datecbButton.setFont(font)
        self.datecbButton.setObjectName("datecbButton")
        self.gridLayout.addWidget(self.datecbButton, 11, 2, 1, 1)
        self.toggleallButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.toggleallButton.setFont(font)
        self.toggleallButton.setObjectName("toggleallButton")
        self.gridLayout.addWidget(self.toggleallButton, 10, 1, 1, 1)
        self.mothercbButton = QtWidgets.QCheckBox(self.centralwidget)
        self.mothercbButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.mothercbButton.setFont(font)
        self.mothercbButton.setObjectName("mothercbButton")
        self.gridLayout.addWidget(self.mothercbButton, 13, 2, 1, 1)
        self.id2Entry = QtWidgets.QLineEdit(self.centralwidget)
        self.id2Entry.setObjectName("id2Entry")
        self.gridLayout.addWidget(self.id2Entry, 7, 2, 1, 2)
        self.name2Entry = QtWidgets.QLineEdit(self.centralwidget)
        self.name2Entry.setObjectName("name2Entry")
        self.gridLayout.addWidget(self.name2Entry, 8, 2, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 7, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 7, 1, 3)
        self.group2Box = QtWidgets.QComboBox(self.centralwidget)
        self.group2Box.setObjectName("group2Box")
        self.gridLayout.addWidget(self.group2Box, 5, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 8, 1, 1, 1)
        self.hoofconcbButton = QtWidgets.QCheckBox(self.centralwidget)
        self.hoofconcbButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hoofconcbButton.setFont(font)
        self.hoofconcbButton.setObjectName("hoofconcbButton")
        self.gridLayout.addWidget(self.hoofconcbButton, 14, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 10, 7, 1, 3)
        self.rfidcbButton = QtWidgets.QCheckBox(self.centralwidget)
        self.rfidcbButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rfidcbButton.setFont(font)
        self.rfidcbButton.setObjectName("rfidcbButton")
        self.gridLayout.addWidget(self.rfidcbButton, 12, 1, 1, 1)
        self.namecbButton = QtWidgets.QCheckBox(self.centralwidget)
        self.namecbButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.namecbButton.setFont(font)
        self.namecbButton.setChecked(True)
        self.namecbButton.setObjectName("namecbButton")
        self.gridLayout.addWidget(self.namecbButton, 11, 1, 1, 1)
        self.fathercbButton = QtWidgets.QCheckBox(self.centralwidget)
        self.fathercbButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fathercbButton.setFont(font)
        self.fathercbButton.setObjectName("fathercbButton")
        self.gridLayout.addWidget(self.fathercbButton, 14, 2, 1, 1)
        self.idcbButton = QtWidgets.QCheckBox(self.centralwidget)
        self.idcbButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.idcbButton.setFont(font)
        self.idcbButton.setObjectName("idcbButton")
        self.gridLayout.addWidget(self.idcbButton, 13, 1, 1, 1)
        self.bdaycbButton = QtWidgets.QCheckBox(self.centralwidget)
        self.bdaycbButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bdaycbButton.setFont(font)
        self.bdaycbButton.setObjectName("bdaycbButton")
        self.gridLayout.addWidget(self.bdaycbButton, 12, 2, 1, 1)
        self.groupcbButton = QtWidgets.QCheckBox(self.centralwidget)
        self.groupcbButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupcbButton.setFont(font)
        self.groupcbButton.setObjectName("groupcbButton")
        self.gridLayout.addWidget(self.groupcbButton, 14, 1, 1, 1)
        self.soldcbButton = QtWidgets.QCheckBox(self.centralwidget)
        self.soldcbButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.soldcbButton.setFont(font)
        self.soldcbButton.setObjectName("soldcbButton")
        self.gridLayout.addWidget(self.soldcbButton, 12, 5, 1, 1)
        self.rfid2Entry = QtWidgets.QLineEdit(self.centralwidget)
        self.rfid2Entry.setObjectName("rfid2Entry")
        self.gridLayout.addWidget(self.rfid2Entry, 6, 2, 1, 2)
        self.notescbButton = QtWidgets.QCheckBox(self.centralwidget)
        self.notescbButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.notescbButton.setFont(font)
        self.notescbButton.setObjectName("notescbButton")
        self.gridLayout.addWidget(self.notescbButton, 11, 5, 1, 1)
        self.weightcbButton = QtWidgets.QCheckBox(self.centralwidget)
        self.weightcbButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.weightcbButton.setFont(font)
        self.weightcbButton.setObjectName("weightcbButton")
        self.gridLayout.addWidget(self.weightcbButton, 12, 3, 1, 1)
        self.gendercbButton = QtWidgets.QCheckBox(self.centralwidget)
        self.gendercbButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gendercbButton.setFont(font)
        self.gendercbButton.setObjectName("gendercbButton")
        self.gridLayout.addWidget(self.gendercbButton, 11, 3, 1, 1)
        self.bodyconcbButton = QtWidgets.QCheckBox(self.centralwidget)
        self.bodyconcbButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bodyconcbButton.setFont(font)
        self.bodyconcbButton.setObjectName("bodyconcbButton")
        self.gridLayout.addWidget(self.bodyconcbButton, 13, 3, 1, 1)
        self.genealogyButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.genealogyButton.setFont(font)
        self.genealogyButton.setObjectName("genealogyButton")
        self.gridLayout.addWidget(self.genealogyButton, 13, 5, 1, 1)
        self.testButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.testButton.setFont(font)
        self.testButton.setObjectName("testButton")
        self.gridLayout.addWidget(self.testButton, 14, 5, 1, 1)
        self.search2Button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.search2Button.setFont(font)
        self.search2Button.setObjectName("search2Button")
        self.gridLayout.addWidget(self.search2Button, 13, 7, 1, 1)
        self.save2Button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.save2Button.setFont(font)
        self.save2Button.setObjectName("save2Button")
        self.gridLayout.addWidget(self.save2Button, 14, 7, 1, 1)
        self.clear2Button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.clear2Button.setFont(font)
        self.clear2Button.setObjectName("clear2Button")
        self.gridLayout.addWidget(self.clear2Button, 13, 8, 1, 1)
        self.quit2Button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.quit2Button.setFont(font)
        self.quit2Button.setObjectName("quit2Button")
        self.gridLayout.addWidget(self.quit2Button, 14, 8, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 1, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Animal Tracker - Advanced Search"))
        self.label_8.setText(_translate("MainWindow", "Table:"))
        self.label_5.setText(_translate("MainWindow", "RFID:"))
        self.label_3.setText(_translate("MainWindow", "Group:"))
        self.distinctcbButton.setText(_translate("MainWindow", "Distinct"))
        self.datecbButton.setText(_translate("MainWindow", "Date"))
        self.toggleallButton.setText(_translate("MainWindow", "Select All"))
        self.mothercbButton.setText(_translate("MainWindow", "Mother"))
        self.label_6.setText(_translate("MainWindow", "ID:"))
        self.label_4.setText(_translate("MainWindow", "Order By:"))
        self.label_7.setText(_translate("MainWindow", "Name:"))
        self.hoofconcbButton.setText(_translate("MainWindow", "Hoof Cond."))
        self.label_9.setText(_translate("MainWindow", "Order By 2:"))
        self.rfidcbButton.setText(_translate("MainWindow", "RFID"))
        self.namecbButton.setText(_translate("MainWindow", "Name"))
        self.fathercbButton.setText(_translate("MainWindow", "Father"))
        self.idcbButton.setText(_translate("MainWindow", "ID"))
        self.bdaycbButton.setText(_translate("MainWindow", "Birthday"))
        self.groupcbButton.setText(_translate("MainWindow", "Group"))
        self.soldcbButton.setText(_translate("MainWindow", "Sold"))
        self.notescbButton.setText(_translate("MainWindow", "Notes"))
        self.weightcbButton.setText(_translate("MainWindow", "Weight"))
        self.gendercbButton.setText(_translate("MainWindow", "Gender"))
        self.bodyconcbButton.setText(_translate("MainWindow", "Body Cond."))
        self.genealogyButton.setText(_translate("MainWindow", "Genealogy"))
        self.testButton.setText(_translate("MainWindow", "Test"))
        self.search2Button.setText(_translate("MainWindow", "Search"))
        self.save2Button.setText(_translate("MainWindow", "Save"))
        self.clear2Button.setText(_translate("MainWindow", "Clear"))
        self.quit2Button.setText(_translate("MainWindow", "Close"))
        self.label.setText(_translate("MainWindow", "Advanced Search"))

