# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'optionswindow3.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(442, 195)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.addgroupButton = QtWidgets.QPushButton(self.centralwidget)
        self.addgroupButton.setObjectName("addgroupButton")
        self.gridLayout.addWidget(self.addgroupButton, 3, 2, 1, 1)
        self.defaultdirEntry = QtWidgets.QLineEdit(self.centralwidget)
        self.defaultdirEntry.setObjectName("defaultdirEntry")
        self.gridLayout.addWidget(self.defaultdirEntry, 2, 1, 1, 1)
        self.addgroupEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.addgroupEdit.setObjectName("addgroupEdit")
        self.gridLayout.addWidget(self.addgroupEdit, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.databaseEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.databaseEdit.setObjectName("databaseEdit")
        self.gridLayout.addWidget(self.databaseEdit, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(160, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 1)
        self.save3Button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.save3Button.setFont(font)
        self.save3Button.setObjectName("save3Button")
        self.gridLayout.addWidget(self.save3Button, 4, 2, 1, 1)
        self.close3Button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.close3Button.setFont(font)
        self.close3Button.setObjectName("close3Button")
        self.gridLayout.addWidget(self.close3Button, 5, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(160, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Animal Tracker - Options"))
        self.addgroupButton.setText(_translate("MainWindow", "Add Group"))
        self.label_4.setText(_translate("MainWindow", "Group: "))
        self.label_3.setText(_translate("MainWindow", "Default Database"))
        self.label_2.setText(_translate("MainWindow", "Default Save Dir"))
        self.save3Button.setText(_translate("MainWindow", "Save"))
        self.close3Button.setText(_translate("MainWindow", "Close"))
        self.label.setText(_translate("MainWindow", "Options"))

