# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!
'''
Copyright © 2018 UnclassedPenguin
App: Animal Tracker
Author: UnclassedPenguin
Description: An app to keep track of your Animals
'''
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(643, 583)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 180, 67, 17))
        self.label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(460, 40, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.notesEntry = QtWidgets.QTextEdit(self.centralwidget)
        self.notesEntry.setGeometry(QtCore.QRect(23, 209, 331, 251))
        self.notesEntry.setObjectName("notesEntry")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 20, 281, 146))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.addgroupButton = QtWidgets.QPushButton(self.layoutWidget)
        self.addgroupButton.setObjectName("addgroupButton")
        self.gridLayout_3.addWidget(self.addgroupButton, 1, 2, 1, 1)
        self.groupBox = QtWidgets.QComboBox(self.layoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3.addWidget(self.groupBox, 1, 1, 1, 1)
        self.rfidEntry = QtWidgets.QLineEdit(self.layoutWidget)
        self.rfidEntry.setObjectName("rfidEntry")
        self.gridLayout_3.addWidget(self.rfidEntry, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 3, 0, 1, 1)
        self.idEntry = QtWidgets.QLineEdit(self.layoutWidget)
        self.idEntry.setObjectName("idEntry")
        self.gridLayout_3.addWidget(self.idEntry, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 4, 0, 1, 1)
        self.nameEntry = QtWidgets.QLineEdit(self.layoutWidget)
        self.nameEntry.setObjectName("nameEntry")
        self.gridLayout_3.addWidget(self.nameEntry, 4, 1, 1, 1)
        self.searchButton = QtWidgets.QPushButton(self.layoutWidget)
        self.searchButton.setObjectName("searchButton")
        self.gridLayout_3.addWidget(self.searchButton, 4, 2, 1, 1)
        self.dateLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dateLabel.setFont(font)
        self.dateLabel.setText("")
        self.dateLabel.setObjectName("dateLabel")
        self.gridLayout_3.addWidget(self.dateLabel, 0, 0, 1, 2)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(270, 470, 351, 89))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.clearButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.clearButton.setObjectName("clearButton")
        self.gridLayout_2.addWidget(self.clearButton, 1, 1, 1, 1)
        self.quitButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.quitButton.setObjectName("quitButton")
        self.gridLayout_2.addWidget(self.quitButton, 2, 2, 1, 1)
        self.testButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.testButton.setObjectName("testButton")
        self.gridLayout_2.addWidget(self.testButton, 2, 1, 1, 1)
        self.advsearchButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.advsearchButton.setObjectName("advsearchButton")
        self.gridLayout_2.addWidget(self.advsearchButton, 1, 2, 1, 1)
        self.optionsButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.optionsButton.setObjectName("optionsButton")
        self.gridLayout_2.addWidget(self.optionsButton, 0, 2, 1, 1)
        self.saveButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout_2.addWidget(self.saveButton, 0, 1, 1, 1)
        self.displayallButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.displayallButton.setObjectName("displayallButton")
        self.gridLayout_2.addWidget(self.displayallButton, 1, 0, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(370, 60, 251, 395))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.layoutWidget2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 3)
        self.motherEntry = QtWidgets.QLineEdit(self.layoutWidget2)
        self.motherEntry.setObjectName("motherEntry")
        self.gridLayout.addWidget(self.motherEntry, 2, 0, 1, 1)
        self.fatherEntry = QtWidgets.QLineEdit(self.layoutWidget2)
        self.fatherEntry.setObjectName("fatherEntry")
        self.gridLayout.addWidget(self.fatherEntry, 2, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 2, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 4, 0, 1, 3)
        self.weightEntry = QtWidgets.QLineEdit(self.layoutWidget2)
        self.weightEntry.setObjectName("weightEntry")
        self.gridLayout.addWidget(self.weightEntry, 5, 0, 1, 1)
        self.bdayEntry = QtWidgets.QLineEdit(self.layoutWidget2)
        self.bdayEntry.setObjectName("bdayEntry")
        self.gridLayout.addWidget(self.bdayEntry, 5, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 6, 0, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout.addWidget(self.line_10, 6, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 6, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 7, 0, 1, 3)
        self.genderButton3 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.genderButton3.setChecked(True)
        self.genderButton3.setObjectName("genderButton3")
        self.genderGroup = QtWidgets.QButtonGroup(MainWindow)
        self.genderGroup.setObjectName("genderGroup")
        self.genderGroup.addButton(self.genderButton3)
        self.gridLayout.addWidget(self.genderButton3, 8, 0, 1, 1)
        self.bodyconButton5 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.bodyconButton5.setChecked(True)
        self.bodyconButton5.setObjectName("bodyconButton5")
        self.bodyconGroup = QtWidgets.QButtonGroup(MainWindow)
        self.bodyconGroup.setObjectName("bodyconGroup")
        self.bodyconGroup.addButton(self.bodyconButton5)
        self.gridLayout.addWidget(self.bodyconButton5, 8, 2, 1, 1)
        self.genderButton2 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.genderButton2.setObjectName("genderButton2")
        self.genderGroup.addButton(self.genderButton2)
        self.gridLayout.addWidget(self.genderButton2, 9, 0, 1, 1)
        self.bodyconButton4 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.bodyconButton4.setObjectName("bodyconButton4")
        self.bodyconGroup.addButton(self.bodyconButton4)
        self.gridLayout.addWidget(self.bodyconButton4, 9, 2, 1, 1)
        self.genderButton1 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.genderButton1.setObjectName("genderButton1")
        self.genderGroup.addButton(self.genderButton1)
        self.gridLayout.addWidget(self.genderButton1, 10, 0, 1, 1)
        self.bodyconButton3 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.bodyconButton3.setObjectName("bodyconButton3")
        self.bodyconGroup.addButton(self.bodyconButton3)
        self.gridLayout.addWidget(self.bodyconButton3, 10, 2, 1, 1)
        self.bodyconButton2 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.bodyconButton2.setObjectName("bodyconButton2")
        self.bodyconGroup.addButton(self.bodyconButton2)
        self.gridLayout.addWidget(self.bodyconButton2, 11, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 12, 0, 1, 1)
        self.bodyconButton1 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.bodyconButton1.setObjectName("bodyconButton1")
        self.bodyconGroup.addButton(self.bodyconButton1)
        self.gridLayout.addWidget(self.bodyconButton1, 12, 2, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 13, 0, 1, 3)
        self.hoofconButton3 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.hoofconButton3.setChecked(True)
        self.hoofconButton3.setObjectName("hoofconButton3")
        self.hoofconGroup = QtWidgets.QButtonGroup(MainWindow)
        self.hoofconGroup.setObjectName("hoofconGroup")
        self.hoofconGroup.addButton(self.hoofconButton3)
        self.gridLayout.addWidget(self.hoofconButton3, 14, 0, 1, 1)
        self.hoofconButton2 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.hoofconButton2.setObjectName("hoofconButton2")
        self.hoofconGroup.addButton(self.hoofconButton2)
        self.gridLayout.addWidget(self.hoofconButton2, 15, 0, 1, 1)
        self.soldButton = QtWidgets.QCheckBox(self.layoutWidget2)
        self.soldButton.setToolTipDuration(-3)
        self.soldButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.soldButton.setObjectName("soldButton")
        self.gridLayout.addWidget(self.soldButton, 15, 2, 1, 1)
        self.hoofconButton1 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.hoofconButton1.setObjectName("hoofconButton1")
        self.hoofconGroup.addButton(self.hoofconButton1)
        self.gridLayout.addWidget(self.hoofconButton1, 16, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Animal Tracker"))
        self.label_6.setText(_translate("MainWindow", "Notes"))
        self.label_7.setText(_translate("MainWindow", "Attributes"))
        self.label_2.setText(_translate("MainWindow", "RFID:"))
        self.label.setText(_translate("MainWindow", "Group"))
        self.addgroupButton.setText(_translate("MainWindow", "Add Group"))
        self.label_3.setText(_translate("MainWindow", "ID:"))
        self.label_4.setText(_translate("MainWindow", "Name:"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.quitButton.setText(_translate("MainWindow", "Quit"))
        self.testButton.setText(_translate("MainWindow", "Test"))
        self.advsearchButton.setText(_translate("MainWindow", "Adv. Search"))
        self.optionsButton.setText(_translate("MainWindow", "Options"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.displayallButton.setText(_translate("MainWindow", "Display All"))
        self.label_8.setText(_translate("MainWindow", "Mother"))
        self.label_9.setText(_translate("MainWindow", "Father"))
        self.label_10.setText(_translate("MainWindow", "Weight"))
        self.label_11.setText(_translate("MainWindow", "Birthday"))
        self.label_12.setText(_translate("MainWindow", "Gender"))
        self.label_13.setText(_translate("MainWindow", "Body Condition"))
        self.genderButton3.setText(_translate("MainWindow", "Female"))
        self.bodyconButton5.setText(_translate("MainWindow", "5 (Good)"))
        self.genderButton2.setText(_translate("MainWindow", "Male"))
        self.bodyconButton4.setText(_translate("MainWindow", "4"))
        self.genderButton1.setText(_translate("MainWindow", "Weather"))
        self.bodyconButton3.setText(_translate("MainWindow", "3"))
        self.bodyconButton2.setText(_translate("MainWindow", "2"))
        self.label_14.setText(_translate("MainWindow", "Hoof Condition"))
        self.bodyconButton1.setText(_translate("MainWindow", "1 (Bad)"))
        self.hoofconButton3.setText(_translate("MainWindow", "Good"))
        self.hoofconButton2.setText(_translate("MainWindow", "OK"))
        self.soldButton.setText(_translate("MainWindow", "Sold"))
        self.hoofconButton1.setText(_translate("MainWindow", "Bad"))

